# Generated by Django 3.0.6 on 2020-06-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_contactinfo3_studentiii_teacheriii'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd1', models.CharField(max_length=256)),
                ('fd2', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.Parent1')),
                ('fd3', models.CharField(max_length=256)),
                ('fd4', models.CharField(max_length=256)),
            ],
            bases=('testapp.parent1',),
        ),
        migrations.CreateModel(
            name='SubChild',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.Child')),
                ('fd5', models.CharField(max_length=256)),
            ],
            bases=('testapp.child',),
        ),
    ]
