# Generated by Django 3.0.6 on 2020-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=20)),
                ('actor', models.CharField(max_length=20)),
                ('actress', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
