# Generated by Django 3.0.6 on 2020-05-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter',
            new_name='Filtermodel',
        ),
    ]
