# Generated by Django 3.0.6 on 2020-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srollno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('sdept', models.CharField(max_length=30)),
            ],
        ),
    ]
